# Models package
from app.models.auth import Message, NewPassword, Token, TokenPayload
from app.models.character import (
    Character,
    CharacterBase,
    CharacterCreate,
    CharacterEmbedding,
    CharacterEmbeddingBase,
    CharacterEmbeddingCreate,
    CharacterEmbeddingPublic,
    CharacterPublic,
    CharacterSearchRequest,
    CharacterSearchResponse,
    CharacterSearchResult,
    CharactersPublic,
    CharacterTag,
    CharacterTagBase,
    CharacterTagCreate,
    CharacterTagMap,
    CharacterTagMapBase,
    CharacterTagPublic,
    CharacterTagUpdate,
    CharacterUpdate,
)
from app.models.item import (
    Item,
    ItemBase,
    ItemCreate,
    ItemPublic,
    ItemsPublic,
    ItemUpdate,
)
from app.models.user import (
    UpdatePassword,
    User,
    UserBase,
    UserCreate,
    UserPublic,
    UserRegister,
    UsersPublic,
    UserUpdate,
    UserUpdateMe,
)

__all__ = [
    # User models
    "User",
    "UserBase",
    "UserCreate",
    "UserPublic",
    "UserRegister",
    "UserUpdate",
    "UserUpdateMe",
    "UpdatePassword",
    "UsersPublic",
    # Item models
    "Item",
    "ItemBase",
    "ItemCreate",
    "ItemPublic",
    "ItemUpdate",
    "ItemsPublic",
    # Character models
    "Character",
    "CharacterBase",
    "CharacterCreate",
    "CharacterPublic",
    "CharacterUpdate",
    "CharactersPublic",
    "CharacterTag",
    "CharacterTagBase",
    "CharacterTagCreate",
    "CharacterTagPublic",
    "CharacterTagUpdate",
    "CharacterTagMap",
    "CharacterTagMapBase",
    "CharacterEmbedding",
    "CharacterEmbeddingBase",
    "CharacterEmbeddingCreate",
    "CharacterEmbeddingPublic",
    "CharacterSearchRequest",
    "CharacterSearchResponse",
    "CharacterSearchResult",
    # Auth models
    "Message",
    "NewPassword",
    "Token",
    "TokenPayload",
]
