"""add_character_models_v2

Revision ID: 42a230188bee
Revises: 92103c25149f
Create Date: 2025-09-22 13:46:16.351872

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42a230188bee'
down_revision = '92103c25149f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建角色标签表
    op.create_table('character_tags',
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('color', sa.String(length=7), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_character_tags_name'), 'character_tags', ['name'], unique=False)
    
    # 创建角色表
    op.create_table('characters',
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('short_bio', sa.String(length=500), nullable=False),
        sa.Column('avatar_url', sa.String(length=500), nullable=True),
        sa.Column('persona_text', sa.Text(), nullable=False),
        sa.Column('example_lines', sa.JSON(), nullable=True),
        sa.Column('source', sa.String(length=200), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    
    # 创建角色-标签关系表
    op.create_table('character_tag_maps',
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.Column('character_id', postgresql.UUID(), nullable=False),
        sa.Column('tag_id', postgresql.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['character_tags.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建角色向量表
    op.create_table('character_embeddings',
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.Column('character_id', postgresql.UUID(), nullable=False),
        sa.Column('embedding_type', sa.String(length=50), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('dimension', sa.Integer(), nullable=False),
        sa.Column('embedding', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_embeddings')
    op.drop_table('character_tag_maps')
    op.drop_table('characters')
    op.drop_table('character_tags')
    # ### end Alembic commands ###