"""add_default_voice_to_character

Revision ID: 54e9f8e460e3
Revises: bd5380ce070b
Create Date: 2025-09-25 00:22:43.076229

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54e9f8e460e3'
down_revision = 'bd5380ce070b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multi_character_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_response_at', sa.DateTime(), nullable=True),
    sa.Column('response_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_image_messages_created_at'), table_name='image_messages')
    op.drop_index(op.f('idx_image_messages_format'), table_name='image_messages')
    op.drop_index(op.f('idx_image_messages_message_id'), table_name='image_messages')
    op.drop_index(op.f('idx_image_messages_status'), table_name='image_messages')
    op.drop_table('image_messages')
    op.drop_index(op.f('idx_file_messages_created_at'), table_name='file_messages')
    op.drop_index(op.f('idx_file_messages_message_id'), table_name='file_messages')
    op.drop_index(op.f('idx_file_messages_security'), table_name='file_messages')
    op.drop_index(op.f('idx_file_messages_status'), table_name='file_messages')
    op.drop_index(op.f('idx_file_messages_type'), table_name='file_messages')
    op.drop_table('file_messages')
    op.drop_index(op.f('idx_file_tasks_file_message_id'), table_name='file_processing_tasks')
    op.drop_index(op.f('idx_file_tasks_image_message_id'), table_name='file_processing_tasks')
    op.drop_index(op.f('idx_file_tasks_status'), table_name='file_processing_tasks')
    op.drop_index(op.f('idx_file_tasks_type'), table_name='file_processing_tasks')
    op.drop_table('file_processing_tasks')
    op.add_column('characters', sa.Column('default_voice', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.drop_index(op.f('ix_voice_catalog_provider'), table_name='voice_catalog')
    op.drop_constraint(op.f('uq_voice_catalog_provider_voice'), 'voice_catalog', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_voice_catalog_provider_voice'), 'voice_catalog', ['provider', 'voice'])
    op.create_index(op.f('ix_voice_catalog_provider'), 'voice_catalog', ['provider'], unique=False)
    op.drop_column('characters', 'default_voice')
    op.create_table('file_processing_tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('image_message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_type', postgresql.ENUM('image_compress', 'image_resize', 'image_format_convert', 'file_scan', 'thumbnail_generate', name='tasktype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='processingstatus'), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name=op.f('check_progress_range')),
    sa.ForeignKeyConstraint(['file_message_id'], ['file_messages.id'], name=op.f('file_processing_tasks_file_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_message_id'], ['image_messages.id'], name=op.f('file_processing_tasks_image_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('file_processing_tasks_pkey'))
    )
    op.create_index(op.f('idx_file_tasks_type'), 'file_processing_tasks', ['task_type'], unique=False)
    op.create_index(op.f('idx_file_tasks_status'), 'file_processing_tasks', ['status'], unique=False)
    op.create_index(op.f('idx_file_tasks_image_message_id'), 'file_processing_tasks', ['image_message_id'], unique=False)
    op.create_index(op.f('idx_file_tasks_file_message_id'), 'file_processing_tasks', ['file_message_id'], unique=False)
    op.create_table('file_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_extension', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('file_type', postgresql.ENUM('document', 'image', 'video', 'audio', 'archive', 'other', name='filetype'), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('preview_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('download_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('processing_status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='processingstatus'), autoincrement=False, nullable=False),
    sa.Column('security_scan_status', postgresql.ENUM('pending', 'scanning', 'safe', 'unsafe', 'failed', name='securityscanstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('download_count >= 0', name=op.f('check_download_count_non_negative')),
    sa.CheckConstraint('file_size > 0', name=op.f('check_file_size_positive')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('file_messages_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('file_messages_pkey'))
    )
    op.create_index(op.f('idx_file_messages_type'), 'file_messages', ['file_type'], unique=False)
    op.create_index(op.f('idx_file_messages_status'), 'file_messages', ['processing_status'], unique=False)
    op.create_index(op.f('idx_file_messages_security'), 'file_messages', ['security_scan_status'], unique=False)
    op.create_index(op.f('idx_file_messages_message_id'), 'file_messages', ['message_id'], unique=False)
    op.create_index(op.f('idx_file_messages_created_at'), 'file_messages', ['created_at'], unique=False)
    op.create_table('image_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('format', postgresql.ENUM('jpeg', 'png', 'gif', 'webp', 'bmp', name='imageformat'), autoincrement=False, nullable=False),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('compressed_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processing_status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='processingstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('file_size > 0', name=op.f('check_file_size_positive')),
    sa.CheckConstraint('height > 0', name=op.f('check_height_positive')),
    sa.CheckConstraint('quality_score >= 0::double precision AND quality_score <= 1::double precision', name=op.f('check_quality_score_range')),
    sa.CheckConstraint('width > 0', name=op.f('check_width_positive')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('image_messages_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('image_messages_pkey'))
    )
    op.create_index(op.f('idx_image_messages_status'), 'image_messages', ['processing_status'], unique=False)
    op.create_index(op.f('idx_image_messages_message_id'), 'image_messages', ['message_id'], unique=False)
    op.create_index(op.f('idx_image_messages_format'), 'image_messages', ['format'], unique=False)
    op.create_index(op.f('idx_image_messages_created_at'), 'image_messages', ['created_at'], unique=False)
    op.drop_table('multi_character_conversations')
    # ### end Alembic commands ###
