"""add_user_profile_fields

Revision ID: 7847618e9b56
Revises: 54e9f8e460e3
Create Date: 2025-09-25 08:55:27.710399

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "7847618e9b56"
down_revision = "54e9f8e460e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "avatar_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
    )
    op.add_column(
        "user",
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column(
            "location", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "website", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
    )
    # 先添加可空的created_at字段
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=True))
    # 为现有记录设置默认的created_at值
    op.execute('UPDATE "user" SET created_at = NOW() WHERE created_at IS NULL')
    # 将created_at字段设置为非空
    op.alter_column("user", "created_at", nullable=False)
    op.add_column(
        "user",
        sa.Column("character_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "user",
        sa.Column(
            "conversation_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "conversation_count")
    op.drop_column("user", "character_count")
    op.drop_column("user", "created_at")
    op.drop_column("user", "website")
    op.drop_column("user", "location")
    op.drop_column("user", "bio")
    op.drop_column("user", "avatar_url")
    # ### end Alembic commands ###
