"""add_user_character_relation

Revision ID: 8672a1de7b3c
Revises: 7847618e9b56
Create Date: 2025-09-25 09:05:51.379444

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "8672a1de7b3c"
down_revision = "7847618e9b56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空的user_id字段
    op.add_column("characters", sa.Column("user_id", sa.Uuid(), nullable=True))

    # 为现有角色设置默认用户（假设存在超级用户）
    # 这里需要根据实际情况调整，可能需要先创建一个默认用户
    op.execute(
        """
        UPDATE characters 
        SET user_id = (SELECT id FROM "user" WHERE is_superuser = true LIMIT 1)
        WHERE user_id IS NULL
    """
    )

    # 将user_id字段设置为非空
    op.alter_column("characters", "user_id", nullable=False)

    # 创建外键约束
    op.create_foreign_key(
        "fk_characters_user_id", "characters", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_characters_user_id", "characters", type_="foreignkey")
    op.drop_column("characters", "user_id")
    # ### end Alembic commands ###
