"""add_character_models

Revision ID: 92103c25149f
Revises: b62fb084efe3
Create Date: 2025-09-22 13:45:54.797376

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '92103c25149f'
down_revision = 'b62fb084efe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
