"""add_character_public_field

Revision ID: b107d9effde2
Revises: 8672a1de7b3c
Create Date: 2025-09-25 09:15:55.734635

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "b107d9effde2"
down_revision = "8672a1de7b3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空的is_public字段
    op.add_column("characters", sa.Column("is_public", sa.Boolean(), nullable=True))

    # 为现有角色设置默认值（默认不公开）
    op.execute("UPDATE characters SET is_public = false WHERE is_public IS NULL")

    # 将is_public字段设置为非空
    op.alter_column("characters", "is_public", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "is_public")
    # ### end Alembic commands ###
