"""Add conversation and message tables

Revision ID: d6f99dbc32f7
Revises: ebc7f1871709
Create Date: 2025-09-23 08:47:53.388068

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd6f99dbc32f7'
down_revision = 'ebc7f1871709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
