/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as CreateAgentIndexRouteImport } from './routes/create-agent/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as IdIndexRouteImport } from './routes/$id/index'
import { Route as CreateAgentLayoutRouteImport } from './routes/create-agent/_layout'
import { Route as CreateAgentLayoutSelfRouteImport } from './routes/create-agent/_layout/self'
import { Route as CreateAgentLayoutIpRouteImport } from './routes/create-agent/_layout/ip'

const CreateAgentRouteImport = createFileRoute('/create-agent')()

const CreateAgentRoute = CreateAgentRouteImport.update({
  id: '/create-agent',
  path: '/create-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAgentIndexRoute = CreateAgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateAgentRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const IdIndexRoute = IdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAgentLayoutRoute = CreateAgentLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => CreateAgentRoute,
} as any)
const CreateAgentLayoutSelfRoute = CreateAgentLayoutSelfRouteImport.update({
  id: '/self',
  path: '/self',
  getParentRoute: () => CreateAgentLayoutRoute,
} as any)
const CreateAgentLayoutIpRoute = CreateAgentLayoutIpRouteImport.update({
  id: '/ip',
  path: '/ip',
  getParentRoute: () => CreateAgentLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/create-agent': typeof CreateAgentLayoutRouteWithChildren
  '/$id': typeof IdIndexRoute
  '/': typeof LayoutIndexRoute
  '/create-agent/': typeof CreateAgentIndexRoute
  '/create-agent/ip': typeof CreateAgentLayoutIpRoute
  '/create-agent/self': typeof CreateAgentLayoutSelfRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/create-agent': typeof CreateAgentIndexRoute
  '/$id': typeof IdIndexRoute
  '/': typeof LayoutIndexRoute
  '/create-agent/ip': typeof CreateAgentLayoutIpRoute
  '/create-agent/self': typeof CreateAgentLayoutSelfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/create-agent': typeof CreateAgentRouteWithChildren
  '/create-agent/_layout': typeof CreateAgentLayoutRouteWithChildren
  '/$id/': typeof IdIndexRoute
  '/_layout/': typeof LayoutIndexRoute
  '/create-agent/': typeof CreateAgentIndexRoute
  '/create-agent/_layout/ip': typeof CreateAgentLayoutIpRoute
  '/create-agent/_layout/self': typeof CreateAgentLayoutSelfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/create-agent'
    | '/$id'
    | '/'
    | '/create-agent/'
    | '/create-agent/ip'
    | '/create-agent/self'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/create-agent'
    | '/$id'
    | '/'
    | '/create-agent/ip'
    | '/create-agent/self'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/create-agent'
    | '/create-agent/_layout'
    | '/$id/'
    | '/_layout/'
    | '/create-agent/'
    | '/create-agent/_layout/ip'
    | '/create-agent/_layout/self'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  CreateAgentRoute: typeof CreateAgentRouteWithChildren
  IdIndexRoute: typeof IdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create-agent': {
      id: '/create-agent'
      path: '/create-agent'
      fullPath: '/create-agent'
      preLoaderRoute: typeof CreateAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-agent/': {
      id: '/create-agent/'
      path: '/'
      fullPath: '/create-agent/'
      preLoaderRoute: typeof CreateAgentIndexRouteImport
      parentRoute: typeof CreateAgentRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/$id/': {
      id: '/$id/'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-agent/_layout': {
      id: '/create-agent/_layout'
      path: '/create-agent'
      fullPath: '/create-agent'
      preLoaderRoute: typeof CreateAgentLayoutRouteImport
      parentRoute: typeof CreateAgentRoute
    }
    '/create-agent/_layout/self': {
      id: '/create-agent/_layout/self'
      path: '/self'
      fullPath: '/create-agent/self'
      preLoaderRoute: typeof CreateAgentLayoutSelfRouteImport
      parentRoute: typeof CreateAgentLayoutRoute
    }
    '/create-agent/_layout/ip': {
      id: '/create-agent/_layout/ip'
      path: '/ip'
      fullPath: '/create-agent/ip'
      preLoaderRoute: typeof CreateAgentLayoutIpRouteImport
      parentRoute: typeof CreateAgentLayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface CreateAgentLayoutRouteChildren {
  CreateAgentLayoutIpRoute: typeof CreateAgentLayoutIpRoute
  CreateAgentLayoutSelfRoute: typeof CreateAgentLayoutSelfRoute
}

const CreateAgentLayoutRouteChildren: CreateAgentLayoutRouteChildren = {
  CreateAgentLayoutIpRoute: CreateAgentLayoutIpRoute,
  CreateAgentLayoutSelfRoute: CreateAgentLayoutSelfRoute,
}

const CreateAgentLayoutRouteWithChildren =
  CreateAgentLayoutRoute._addFileChildren(CreateAgentLayoutRouteChildren)

interface CreateAgentRouteChildren {
  CreateAgentLayoutRoute: typeof CreateAgentLayoutRouteWithChildren
  CreateAgentIndexRoute: typeof CreateAgentIndexRoute
}

const CreateAgentRouteChildren: CreateAgentRouteChildren = {
  CreateAgentLayoutRoute: CreateAgentLayoutRouteWithChildren,
  CreateAgentIndexRoute: CreateAgentIndexRoute,
}

const CreateAgentRouteWithChildren = CreateAgentRoute._addFileChildren(
  CreateAgentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  CreateAgentRoute: CreateAgentRouteWithChildren,
  IdIndexRoute: IdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
