/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as CreateAgentLayoutRouteImport } from './routes/create-agent/_layout'
import { Route as IdLayoutRouteImport } from './routes/$id/_layout'
import { Route as CreateAgentLayoutIndexRouteImport } from './routes/create-agent/_layout/index'
import { Route as IdLayoutIndexRouteImport } from './routes/$id/_layout/index'
import { Route as CreateAgentLayoutSelfRouteImport } from './routes/create-agent/_layout/self'
import { Route as CreateAgentLayoutIpRouteImport } from './routes/create-agent/_layout/ip'
import { Route as IdLayoutPhoneRouteImport } from './routes/$id/_layout/phone'

const CreateAgentRouteImport = createFileRoute('/create-agent')()
const IdRouteImport = createFileRoute('/$id')()

const CreateAgentRoute = CreateAgentRouteImport.update({
  id: '/create-agent',
  path: '/create-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const CreateAgentLayoutRoute = CreateAgentLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => CreateAgentRoute,
} as any)
const IdLayoutRoute = IdLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => IdRoute,
} as any)
const CreateAgentLayoutIndexRoute = CreateAgentLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateAgentLayoutRoute,
} as any)
const IdLayoutIndexRoute = IdLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdLayoutRoute,
} as any)
const CreateAgentLayoutSelfRoute = CreateAgentLayoutSelfRouteImport.update({
  id: '/self',
  path: '/self',
  getParentRoute: () => CreateAgentLayoutRoute,
} as any)
const CreateAgentLayoutIpRoute = CreateAgentLayoutIpRouteImport.update({
  id: '/ip',
  path: '/ip',
  getParentRoute: () => CreateAgentLayoutRoute,
} as any)
const IdLayoutPhoneRoute = IdLayoutPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => IdLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRoute
  '/$id': typeof IdLayoutRouteWithChildren
  '/create-agent': typeof CreateAgentLayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/$id/phone': typeof IdLayoutPhoneRoute
  '/create-agent/ip': typeof CreateAgentLayoutIpRoute
  '/create-agent/self': typeof CreateAgentLayoutSelfRoute
  '/$id/': typeof IdLayoutIndexRoute
  '/create-agent/': typeof CreateAgentLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRoute
  '/$id': typeof IdLayoutIndexRoute
  '/create-agent': typeof CreateAgentLayoutIndexRoute
  '/': typeof LayoutIndexRoute
  '/$id/phone': typeof IdLayoutPhoneRoute
  '/create-agent/ip': typeof CreateAgentLayoutIpRoute
  '/create-agent/self': typeof CreateAgentLayoutSelfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRoute
  '/$id': typeof IdRouteWithChildren
  '/$id/_layout': typeof IdLayoutRouteWithChildren
  '/create-agent': typeof CreateAgentRouteWithChildren
  '/create-agent/_layout': typeof CreateAgentLayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/$id/_layout/phone': typeof IdLayoutPhoneRoute
  '/create-agent/_layout/ip': typeof CreateAgentLayoutIpRoute
  '/create-agent/_layout/self': typeof CreateAgentLayoutSelfRoute
  '/$id/_layout/': typeof IdLayoutIndexRoute
  '/create-agent/_layout/': typeof CreateAgentLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/user'
    | '/$id'
    | '/create-agent'
    | '/'
    | '/$id/phone'
    | '/create-agent/ip'
    | '/create-agent/self'
    | '/$id/'
    | '/create-agent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/user'
    | '/$id'
    | '/create-agent'
    | '/'
    | '/$id/phone'
    | '/create-agent/ip'
    | '/create-agent/self'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/user'
    | '/$id'
    | '/$id/_layout'
    | '/create-agent'
    | '/create-agent/_layout'
    | '/_layout/'
    | '/$id/_layout/phone'
    | '/create-agent/_layout/ip'
    | '/create-agent/_layout/self'
    | '/$id/_layout/'
    | '/create-agent/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UserRoute: typeof UserRoute
  IdRoute: typeof IdRouteWithChildren
  CreateAgentRoute: typeof CreateAgentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create-agent': {
      id: '/create-agent'
      path: '/create-agent'
      fullPath: '/create-agent'
      preLoaderRoute: typeof CreateAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/create-agent/_layout': {
      id: '/create-agent/_layout'
      path: '/create-agent'
      fullPath: '/create-agent'
      preLoaderRoute: typeof CreateAgentLayoutRouteImport
      parentRoute: typeof CreateAgentRoute
    }
    '/$id/_layout': {
      id: '/$id/_layout'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdLayoutRouteImport
      parentRoute: typeof IdRoute
    }
    '/create-agent/_layout/': {
      id: '/create-agent/_layout/'
      path: '/'
      fullPath: '/create-agent/'
      preLoaderRoute: typeof CreateAgentLayoutIndexRouteImport
      parentRoute: typeof CreateAgentLayoutRoute
    }
    '/$id/_layout/': {
      id: '/$id/_layout/'
      path: '/'
      fullPath: '/$id/'
      preLoaderRoute: typeof IdLayoutIndexRouteImport
      parentRoute: typeof IdLayoutRoute
    }
    '/create-agent/_layout/self': {
      id: '/create-agent/_layout/self'
      path: '/self'
      fullPath: '/create-agent/self'
      preLoaderRoute: typeof CreateAgentLayoutSelfRouteImport
      parentRoute: typeof CreateAgentLayoutRoute
    }
    '/create-agent/_layout/ip': {
      id: '/create-agent/_layout/ip'
      path: '/ip'
      fullPath: '/create-agent/ip'
      preLoaderRoute: typeof CreateAgentLayoutIpRouteImport
      parentRoute: typeof CreateAgentLayoutRoute
    }
    '/$id/_layout/phone': {
      id: '/$id/_layout/phone'
      path: '/phone'
      fullPath: '/$id/phone'
      preLoaderRoute: typeof IdLayoutPhoneRouteImport
      parentRoute: typeof IdLayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface IdLayoutRouteChildren {
  IdLayoutPhoneRoute: typeof IdLayoutPhoneRoute
  IdLayoutIndexRoute: typeof IdLayoutIndexRoute
}

const IdLayoutRouteChildren: IdLayoutRouteChildren = {
  IdLayoutPhoneRoute: IdLayoutPhoneRoute,
  IdLayoutIndexRoute: IdLayoutIndexRoute,
}

const IdLayoutRouteWithChildren = IdLayoutRoute._addFileChildren(
  IdLayoutRouteChildren,
)

interface IdRouteChildren {
  IdLayoutRoute: typeof IdLayoutRouteWithChildren
}

const IdRouteChildren: IdRouteChildren = {
  IdLayoutRoute: IdLayoutRouteWithChildren,
}

const IdRouteWithChildren = IdRoute._addFileChildren(IdRouteChildren)

interface CreateAgentLayoutRouteChildren {
  CreateAgentLayoutIpRoute: typeof CreateAgentLayoutIpRoute
  CreateAgentLayoutSelfRoute: typeof CreateAgentLayoutSelfRoute
  CreateAgentLayoutIndexRoute: typeof CreateAgentLayoutIndexRoute
}

const CreateAgentLayoutRouteChildren: CreateAgentLayoutRouteChildren = {
  CreateAgentLayoutIpRoute: CreateAgentLayoutIpRoute,
  CreateAgentLayoutSelfRoute: CreateAgentLayoutSelfRoute,
  CreateAgentLayoutIndexRoute: CreateAgentLayoutIndexRoute,
}

const CreateAgentLayoutRouteWithChildren =
  CreateAgentLayoutRoute._addFileChildren(CreateAgentLayoutRouteChildren)

interface CreateAgentRouteChildren {
  CreateAgentLayoutRoute: typeof CreateAgentLayoutRouteWithChildren
}

const CreateAgentRouteChildren: CreateAgentRouteChildren = {
  CreateAgentLayoutRoute: CreateAgentLayoutRouteWithChildren,
}

const CreateAgentRouteWithChildren = CreateAgentRoute._addFileChildren(
  CreateAgentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UserRoute: UserRoute,
  IdRoute: IdRouteWithChildren,
  CreateAgentRoute: CreateAgentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
